# name: Streamlit CI/CD

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main

# jobs:
#   build-and-test:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v3

#       - name: Set up Python
#         uses: actions/setup-python@v4
#         with:
#           python-version: "3.10"

#       - name: Install dependencies
#         run: |
#           pip install --upgrade pip
#           pip install -r requirements.txt

#       - name: Lint with flake8
#         run: |
#           flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
#           flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

#       - name: Run tests
#         run: pytest

#       - name: Run Streamlit app (headless check)
#         run: |
#           streamlit run webapp/pages/mlops-endsem.py --server.headless true &
#           sleep 10
#           pkill streamlit
